name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          
      - name: Authenticate with npm
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        
      - name: Install dependencies
        run: npm ci
        
      - name: Install Package dependencies
        run: cd projects/ion-star-ratings && npm ci
        
      - name: Build Generate
        run: npm run build
        
      - name: Go to build folder
        run: cd dist/ion-star-ratings
      
      - name: Publish the package
        run: npm publish
